version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 20
    commands:
      - npm install -g pnpm
  pre_build:
    commands:
      - pnpm install
  build:
    commands:
      - pnpm run build

artifacts:
  files:
    - '**/*'